[general]
destination = "$HOME/.config/hypr/monitors.conf"

[power_events]

[power_events.dbus_query_object]
path = "/org/freedesktop/UPower/devices/line_power_AC"

[[power_events.dbus_signal_match_rules]]
object_path = "/org/freedesktop/UPower/devices/line_power_AC"


[profiles.desk-setup]
config_file = "/home/emmanuel/.config/hyprdynamicmonitors/hyprconfigs/desk-setup.go.tmpl"
config_file_type = "template"
[profiles.desk-setup.conditions]

[[profiles.desk-setup.conditions.required_monitors]]
description = "Lenovo Group Limited MNE007JA1-3"
monitor_tag = "monitor0"

[[profiles.desk-setup.conditions.required_monitors]]
description = "Samsung Electric Company U32R59x H1AK500000"
monitor_tag = "monitor1"


[profiles.laptop-only]
config_file = "/home/emmanuel/.config/hyprdynamicmonitors/hyprconfigs/laptop-only.go.tmpl"
config_file_type = "template"
[profiles.laptop-only.conditions]

[[profiles.laptop-only.conditions.required_monitors]]
description = "Lenovo Group Limited MNE007JA1-3"
monitor_tag = "monitor0"
